### ISSUE TITLE
Allow for using any name as layer name

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/expo-export#2]
The variable names `name`, `backgroundColor`, `width`, `height`, `Render`, `Text`, `Image`, `Slice9`are specified by system. Using the same name in a layer will result in broken output files.

Here are the conflicting lines
https://github.com/consento-org/expo-export/blob/be067e387d42aedc3e3e738ef6dce4a3c6ed5e0a/assets/styles/Component.tsx#L206-L220

We should _somehow_ support to use any name in a component.

**Comment by martinheidegger** [comment]
We could deal with this in two ways:

1. Use Symbols instead of fields: `elementHeader.name` → `elementHeader[Sketch.name]` which would leave the properties clean
2. Put all the generated elements into a child object: `elementHeader.layers.<myLayerName>`

I am not sure which to use @aruneko do you have a preference?

**Comment by aruneko** [comment]
I love second way since we can use editor completion.
